name: Deploy to Hostinger

on:
  push:
    branches:
      - main   # Runs when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create subdomain in Hostinger
        run: |
          curl -X POST "https://api.hostinger.com/dns-records" \
          -H "Authorization: Bearer ${{ secrets.HOSTINGER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "zone": "vistavisiondevelopers.com",
            "type": "A",
            "name": "app",
            "content": "82.180.143.50",
            "ttl": 3600
          }'

      - name: Deploy app to Hostinger (FTP upload)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.yourdomain.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./   # local GitHub repo
          server-dir: /public_html/app/   # subdomain folder
